--- #YAML:1.0
name:               Net-FTP-File
version:            0.06
abstract:           Perl extension for simplifying FTP file operations.
author:
    - Daniel Muey <http://drmuey.com/cpan_contact.pl>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::FTP:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
