#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-FTP-File
version:      0.05
version_from: File.pm
installdirs:  site
requires:
    Net::FTP:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
